"""empty message

Revision ID: cdf988d2f09c
Revises: b40eda33e7cd
Create Date: 2023-12-03 09:57:51.427110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf988d2f09c'
down_revision = 'b40eda33e7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.String(length=256), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
